---
ID: "483ebfec-f1b9-40cc-9a26-9a675c2a9060"
Parent: "a3e5e09f-1422-4050-9414-dc959aa60d7b"
Template: "5f2c442f-2554-4c80-b1d9-2195fa6168b1"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/Actions/SaveToUserSettings
DB: core
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{5A7CF08C-3647-4F56-B189-9E8C0531FBAF}">
        <r
          id="{DAFAFFB8-74AF-4141-A96A-70B16834CEC6}"
          par="PageCodeScriptFileName=%2fsitecore%2fshell%2fclient%2fApplications%2fFormsBuilder%2fLayouts%2fActions%2fSaveToUserSettings.js&amp;SpeakCoreVersion=%7b3F937240-C16E-4229-9641-4CE5B4CB4ABA%7d"
          ph="Page.Code"
          uid="{3D12BF0D-D7B8-459F-A4F3-878A4764A05C}" />
        <r
          id="{EFCD0AB0-5B9D-4F1D-AB81-BE0336CD273C}"
          par="IsVisible=0&amp;Id=HeaderTitle"
          ph="Page.Body"
          uid="{05F18ECB-6811-4212-9846-202CCC78A2F2}" />
        <r
          id="{EFCD0AB0-5B9D-4F1D-AB81-BE0336CD273C}"
          par="IsVisible=0&amp;Id=HeaderSubtitle"
          ph="Page.Body"
          uid="{10FE1F0C-365B-4267-88FB-75611790D272}" />
        <r
          id="{08994B8F-7BF1-4963-815D-0FA8D75B3D86}"
          par="Id=MainBorder+"
          ph="Page.Body"
          uid="{EAF49FA2-9A69-4C3F-9263-84B618612F35}" />
        <r
          id="{59E2A66D-11D2-488D-A3BC-6C1C81326645}"
          par="FieldDefinitionType=%7b167CCD4C-34CE-4557-985B-0915D86B3D99%7d&amp;FieldsLayout=%7b0F6F5EFF-73B4-4597-A232-F50DF253514E%7d&amp;ConfigurationItem=%7bE7ADD9AE-D464-42A9-92D5-AFDF360CD205%7d&amp;Id=SetAreaForm"
          ph="MainBorder .Content"
          uid="{D2CF0B71-D4B2-450C-869A-F571B2687856}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T133237Z
    - ID: "7205a57f-93b4-413a-aa9a-6b16bbc59565"
      Hint: BrowserTitle
      Value: SaveToUserSettings
