---
ID: "d14acac0-ce67-4f05-8db9-fa143ff4d9c2"
Parent: "891e7268-fa3e-4e74-b4b1-c16b206f2165"
Template: "c2d1d114-3cfe-4558-a9e3-d1a1ec0fcab7"
Path: /sitecore/system/Settings/Forms/Submit Actions/Save To User Settings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/16x16/photo_portrait.png
- ID: "2c6e7306-2871-473a-9149-71443182b8e8"
  Hint: Model Type
  Value: SF.Foundation.Facets.Forms.UserSettingsSubmitAction, SF.Foundation.Facets
- ID: "d83b5c6b-7230-419f-bd75-4e2d20c87a18"
  Hint: Editor
  Value: "{483EBFEC-F1B9-40CC-9A26-9A675C2A9060}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T140539Z
    - ID: "47837625-b3d9-46f1-a73b-ff13dd1c8b25"
      Hint: Error Message
      Value: Save to User Settings Failed
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
