---
ID: "7d34dbea-71cd-4c29-8632-58b47c2a8215"
Parent: "cd182b59-58bf-492f-b9e3-a97a6ab46f26"
Template: "f0d16eee-3a05-4e43-a082-795a32b873c0"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/SF/User Settings Condition
DB: master
SharedFields:
- ID: "ab51c8b2-f0e1-4471-9aae-cc080d774923"
  Hint: Type
  Value: SF.Foundation.Facets.UserSettingsCondition,SF.Foundation.Facets
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171019T210842Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "where the current user has a User Setting for [Area,,Area] and [Key,,Key] that [OperatorId, StringOperator,,compares to] [Value,,,specific value]"
