---
ID: "da340e88-3709-4a05-a5a2-9fb695bd640b"
Parent: "58e439b5-3282-4d8e-aefc-83351b3cd542"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Item Version Trim/Tags/Default
DB: master
BranchID: "9a72c539-dbf8-4dad-96d3-a298fc04add6"
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{22F34DAD-86A8-41FE-B0BB-2DE8AEB0F776}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170318T170113Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
