---
ID: "1eac1627-69e2-42c6-919d-b96a7b87b173"
Parent: "0cfeda0d-df66-45c5-b3aa-154d0005f293"
Template: "0cfeda0d-df66-45c5-b3aa-154d0005f293"
Path: /sitecore/templates/Feature/SF/Preference/Base Templates/_Preference Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200108T192931Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
