---
ID: "0ac6167e-bade-4756-abdb-31aff48c6cb6"
Parent: "0cfeda0d-df66-45c5-b3aa-154d0005f293"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/SF/Preference/Base Templates/_Preference Item/Preference Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200108T192927Z
